---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "bin/*"
exclude_paths:
- "*.md"
- doc/**/*
- gruf.gemspec
- Rakefile
- spec/**/*
