AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

Lint/AmbiguousOperator:
  Exclude:
    - lib/gruf/rspec/configuration.rb

Layout/LineLength:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false
