AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*

Lint/AmbiguousOperator:
  Exclude:
    - lib/gruf/rspec/configuration.rb

Layout/LineLength:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false
