AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*

Lint/AmbiguousOperator:
  Exclude:
    - lib/gruf/rspec/configuration.rb

Layout/LineLength:
  Enabled: false
