AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile
    - gruf-rspec.gemspec

Lint/AmbiguousOperator:
  Exclude:
    - lib/gruf/rspec/configuration.rb

Layout/LineLength:
  Enabled: false
