AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile
    - gruf-rspec.gemspec

# Configuration parameters: AlignWith, SupportedStyles, AutoCorrect.
# SupportedStyles: keyword, variable, start_of_line
Layout/EndAlignment:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/AbcSize:
  Max: 147

Metrics/BlockNesting:
  Max: 4

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 406

Metrics/CyclomaticComplexity:
  Max: 24

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Enabled: false

# Offense count: 63
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 88

# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 1000

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 26

# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
# SupportedStyles: line_count_based, semantic, braces_for_chaining
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# IgnoredMethods: lambda, proc, it
Style/BlockDelimiters:
  Exclude:
    - 'config/deploy.rb'

# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep, IndentationWidth.
# SupportedStyles: case, end
Layout/CaseIndentation:
  Enabled: false

Style/ColonMethodCall:
  Exclude:
    - 'db/seeds.rb'

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Style/Documentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: leading, trailing
Layout/DotPosition:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Because $stats is valid
Style/GlobalVars:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Layout/IndentHash:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Naming/MethodName:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Layout/MultilineMethodCallIndentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Layout/MultilineOperationIndentation:
  Enabled: false

# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Naming/PredicateName:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Enabled: false

# Skip because we want 2.2 support
Style/SafeNavigation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false
