version: 2.1

orbs:
  code-climate: bigcommerce/internal-codeclimate@volatile

ruby_env: &ruby_env
  working_directory: ~/repo
  environment:
    BUNDLE_JOBS: 4
    BUNDLE_RETRY: 3
    BUNDLE_PATH: vendor/bundle
    RACK_ENV: test
    RAILS_ENV: test
    RUBY_VERSION: <<parameters.ruby-version>>
  docker:
    - image: circleci/ruby:<<parameters.ruby-version>>

executors:
  ruby_2_6:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.6"
  ruby_2_7:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "2.7"
  ruby_3_0:
    <<: *ruby_env
    parameters:
      ruby-version:
        type: string
        default: "3.0"

commands:
  pre-setup:
    steps:
      - add_ssh_keys
      - checkout
  bundle-install:
    parameters:
      gem_cache_key:
        type: string
        default: gem-cache-v2
    steps:
      - restore_cache:
          keys:
            - <<parameters.gem_cache_key>>-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - <<parameters.gem_cache_key>>-{{ arch }}-{{ .Branch }}
            - <<parameters.gem_cache_key>>
      - run:
          name: "Bundle install"
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle lock --add-platform x86_64-linux
            bundle check || bundle install
      - save_cache:
          key: <<parameters.gem_cache_key>>-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  rspec-unit:
    parameters:
      additional_args:
        type: string
        default: ""
      glob:
        type: string
        default: ""
      code-climate:
        type: boolean
        default: false
    steps:
      - run: mkdir ~/rspec
      - when:
          condition: <<parameters.code-climate>>
          steps:
            - code-climate/setup
      - run:
          name: "Run rspec tests"
          command: |
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            echo "Running: ${TESTFILES}"
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml <<parameters.additional_args>> -- ${TESTFILES}
          when: always
      - when:
          condition: <<parameters.code-climate>>
          steps:
            - code-climate/store-report:
                coverage-format: "simplecov"
            - code-climate/sum-coverage
            - code-climate/after-build:
                coverage-format: "simplecov"
      - store_test_results:
          path: ~/rspec
  bundle-audit:
    parameters:
      additional_args:
        type: string
        default: ""
    steps:
      - run: bundle exec bundle-audit update
      - run: bundle exec bundle-audit check -v <<parameters.additional_args>>
  rubocop:
    steps:
      - run: bundle exec rubocop -p

jobs:
  bundle-audit:
    executor: <<parameters.e>>
    parameters:
      e:
        type: executor
        default: "ruby_2_6"
    steps:
      - pre-setup
      - bundle-install
      - bundle-audit
  rubocop:
    executor: <<parameters.e>>
    parameters:
      e:
        type: executor
        default: "ruby_2_6"
    steps:
      - pre-setup
      - bundle-install
      - bundle-audit
  rspec-unit:
    executor: <<parameters.e>>
    parameters:
      e:
        type: executor
        default: "ruby_2_6"
      code-climate:
        type: boolean
        default: false
    steps:
      - pre-setup
      - bundle-install
      - rspec-unit:
          code-climate: <<parameters.code-climate>>

workflows:
  version: 2
  ruby_2_6:
    jobs:
      - bundle-audit:
          name: "ruby-2_6-bundle_audit"
          e: "ruby_2_6"
      - rubocop:
          name: "ruby-2_6-rubocop"
          e: "ruby_2_6"
      - rspec-unit:
          name: "ruby-2_6-rspec"
          e: "ruby_2_6"
  ruby_2_7:
    jobs:
      - bundle-audit:
          name: "ruby-2_7-bundle_audit"
          e: "ruby_2_7"
      - rubocop:
          name: "ruby-2_7-rubocop"
          e: "ruby_2_7"
      - rspec-unit:
          name: "ruby-2_7-rspec"
          e: "ruby_2_7"
  ruby_3_0:
    jobs:
      - bundle-audit:
          name: "ruby-3_0-bundle_audit"
          e: "ruby_3_0"
      - rubocop:
          name: "ruby-3_0-rubocop"
          e: "ruby_3_0"
      - rspec-unit:
          name: "ruby-3_0-rspec"
          e: "ruby_3_0"
          code-climate: true
